spring:
  application:
    name: consumer-anno-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.3.67:8848
        username: nacos
        password: nacos
server:
  port: 9030

logging:
  level:
    root: debug


#dubbo:
#  application:
#    name: order-service-dubbo
#  registry:
#    address: nacos://192.168.31.101:8848