seata:
  enabled: true
  tx-service-group: my_test_tx_group
  enable-auto-data-source-proxy: true
  service:
    vgroup-mapping:
      my_test_tx_group: default
    grouplist:
      default: 192.168.3.67:9091
    enable-degrade: false
    disable-global-transaction: false
  config:
    type: nacos
    nacos:
      namespace:
      serverAddr: 192.168.3.67:8848
      group: SEATA_GROUP
      username: nacos
      password: nacos
      cluster: default
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 192.168.3.67:8848
      group : SEATA_GROUP
      namespace:
      username: nacos
      password: nacos
      cluster: default
spring:
  application:
    name: rm-points
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/seata_points?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: 192.168.3.67:8848
  jpa:
    show-sql: true
server:
  port: 8003
logging:
  level:
    io:
      seata: debug
