server:
  port: 8040
# 应用名称
spring:
  application:
    name: warehouse-service
  cloud:
    nacos: #nacos注册地址
      discovery:
        server-addr: 192.168.3.67:8848
        username: nacos
        password: nacos
        namespace: public
dubbo:
  application:
    name: warehouse-dubbo
  registry: #Provider与Nacos通信地址，与spring.cloud.nacos地址一致
    address: nacos://192.168.3.67:8848
  protocol:
    name: dubbo #通信协议名
    port: 20880 #配置通信端口，默认为20880
  scan: #配置Provider启动时扫描包路径
    base-packages: com.lagou.warehouseservice.dubbo


# 这里订阅"自己"，会被忽略掉，请根据实际情况添加
#dubbo.cloud.subscribed-services=warehouse


